-- Initial migration is generated by `prisma migrate dev` against your database.
-- Run:  npm run prisma:migrate --workspace @sms/api
-- This placeholder documents the expected first migration name.
-- After running, commit the generated SQL here.

-- The RLS policies and audit triggers live in prisma/sql/rls_and_audit.sql
-- and must be applied after the schema migration (see README).
